# Copied from https://github.com/yjbanov/flutter_travis_sample with minimal changes
os:
  - linux
sudo: false
addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test # if we don't specify this, the libstdc++6 we get is the wrong version
    packages:
      - libstdc++6
      - fonts-droid-fallback
before_script:
  - git clone https://github.com/flutter/flutter.git
  - ./flutter/bin/flutter doctor
  - ./flutter/bin/flutter pub global activate webdev
script:
  - ./flutter/bin/flutter pub global run webdev build
cache:
  directories:
    - $HOME/.pub-cache
